name: lein_test

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: ['src/**','test/**', 'java/**', 'project.clj']
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths: ['src/**','test/**', 'java/**', 'project.clj']

jobs:
  run-lein-tests:
    name: lein test - Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17', '21' ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Install Leiningen
        uses: DeLaGuardo/setup-clojure@13.2
        with:
          lein: latest
      - name: Run lein tests with dev test profile
        run: lein with-profile dev test
      - name: Run lein tests with fips profile
        run: lein with-profile fips test
